device:
  # whether to use CUDA
  cuda: False
  torch_threads: 4

# max_action:  176
# max_observation:  273

state_type: EP

slot_length: 50
task_num: 100
task_distribution: "uniform"
min_input_data_size_of_tasks: 0.01  # MB
max_input_data_size_of_tasks: 5.0   # MB
min_cpu_cycles_of_tasks: 100        # cycles/bit
max_cpu_cycles_of_tasks: 500        # cycles/bit

vehicle_num: 50
vehicle_mobility_file_name_key: "I-80-Emeryville-CA-1650feet-0500pm-0515pm"
vehicular_trajectories_processing_start_time: "2005-04-13 17:00:00"
vehicular_trajectories_processing_selection_way: "max_duration"
vehicular_trajectories_processing_filling_way: "linear"
vehicular_trajectories_processing_chunk_size: 100000
min_computing_capability_of_vehicles: 10.0         # GHz
max_computing_capability_of_vehicles: 50.0         # GHz
min_storage_capability_of_vehicles: 5.0           # MB
max_storage_capability_of_vehicles: 10.0          # MB
min_transmission_power_of_vehicles: 500.0         # mW
max_transmission_power_of_vehicles: 1000.0        # mW
V2V_distance: 100.0                               # meters
min_task_arrival_rate_of_vehicles: 0.5            # tasks/sec
max_task_arrival_rate_of_vehicles: 1.0            # tasks/sec
vehicle_distribution: "uniform"
server_vehicle_probability: 0.3
task_ids_rate: 0.1                                # 10%

edge_num: 9
min_computing_capability_of_edges: 50.0           # GHz
max_computing_capability_of_edges: 500.0          # GHz
min_storage_capability_of_edges: 20.0             # MB
max_storage_capability_of_edges: 100.0            # MB
min_communication_range_of_edges: 100.0           # meters
max_communication_range_of_edges: 300.0           # meters
I2I_transmission_rate: 100.0                      # Mbps
I2I_transmission_weight: 100.0
I2I_propagation_speed: 200000                     # km/s  about 2/3 speed of light
edge_distribution: "uniform"

cloud_computing_capability: 1000.0                # GHz
cloud_storage_capability: 1000.0                  # MB
min_I2C_wired_bandwidth: 100.0                    # Mbps
max_I2C_wired_bandwidth: 500.0                    # Mbps
I2C_transmission_rate: 1000.0                      # Mbps
I2C_propagation_speed: 225000.0                   # km/s about 3/4 speed of light
cloud_distribution: "uniform"

V2V_bandwidth: 20.0                               # MHz
V2I_bandwidth: 20.0                               # MHz
white_gaussian_noise: -90                         # dBm
path_loss_exponent: 3

seed: 264

penalty_weight: 1                          # 1


